d /var/lib/bingwall 0750 bingwall bingwall -
d /var/lib/bingwall/data 0750 bingwall bingwall -
d /var/lib/bingwall/images 0750 bingwall bingwall -
d /var/lib/bingwall/images/tmp 0750 bingwall bingwall -
d /var/lib/bingwall/images/failed 0750 bingwall bingwall -
d /var/lib/bingwall/images/public 2750 bingwall www-data -
d /var/log/bingwall 0750 bingwall bingwall -
d /var/backups/bingwall 0750 bingwall bingwall -
d /etc/bingwall 0750 bingwall bingwall -
